// Code generated by protoc-gen-go. DO NOT EDIT.
// source: groupcache.proto

package groupcachepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GroupPeerRequest struct {
	Op                   string   `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Group                string   `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupPeerRequest) Reset()         { *m = GroupPeerRequest{} }
func (m *GroupPeerRequest) String() string { return proto.CompactTextString(m) }
func (*GroupPeerRequest) ProtoMessage()    {}
func (*GroupPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba3e029bfa16198, []int{0}
}

func (m *GroupPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupPeerRequest.Unmarshal(m, b)
}
func (m *GroupPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupPeerRequest.Marshal(b, m, deterministic)
}
func (m *GroupPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupPeerRequest.Merge(m, src)
}
func (m *GroupPeerRequest) XXX_Size() int {
	return xxx_messageInfo_GroupPeerRequest.Size(m)
}
func (m *GroupPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupPeerRequest proto.InternalMessageInfo

func (m *GroupPeerRequest) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *GroupPeerRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *GroupPeerRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GroupPeerRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GroupPeerResponse struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Ok                   bool     `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Err                  bool     `protobuf:"varint,3,opt,name=err,proto3" json:"err,omitempty"`
	MinuteQps            float64  `protobuf:"fixed64,4,opt,name=minute_qps,json=minuteQps,proto3" json:"minute_qps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupPeerResponse) Reset()         { *m = GroupPeerResponse{} }
func (m *GroupPeerResponse) String() string { return proto.CompactTextString(m) }
func (*GroupPeerResponse) ProtoMessage()    {}
func (*GroupPeerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba3e029bfa16198, []int{1}
}

func (m *GroupPeerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupPeerResponse.Unmarshal(m, b)
}
func (m *GroupPeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupPeerResponse.Marshal(b, m, deterministic)
}
func (m *GroupPeerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupPeerResponse.Merge(m, src)
}
func (m *GroupPeerResponse) XXX_Size() int {
	return xxx_messageInfo_GroupPeerResponse.Size(m)
}
func (m *GroupPeerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupPeerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupPeerResponse proto.InternalMessageInfo

func (m *GroupPeerResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *GroupPeerResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *GroupPeerResponse) GetErr() bool {
	if m != nil {
		return m.Err
	}
	return false
}

func (m *GroupPeerResponse) GetMinuteQps() float64 {
	if m != nil {
		return m.MinuteQps
	}
	return 0
}

func init() {
	proto.RegisterType((*GroupPeerRequest)(nil), "groupcachepb.GroupPeerRequest")
	proto.RegisterType((*GroupPeerResponse)(nil), "groupcachepb.GroupPeerResponse")
}

func init() { proto.RegisterFile("groupcache.proto", fileDescriptor_aba3e029bfa16198) }

var fileDescriptor_aba3e029bfa16198 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x14, 0xc4, 0x69, 0xaa, 0xd2, 0x3e, 0x8a, 0xd4, 0xe0, 0x21, 0x08, 0xfe, 0xa1, 0x27, 0x4f, 0x3d,
	0xe8, 0x47, 0x10, 0xf1, 0xa8, 0xc6, 0x0f, 0xa0, 0x6d, 0x79, 0xa8, 0xdb, 0xdd, 0xe6, 0x35, 0x69,
	0x16, 0xf6, 0xdb, 0x2f, 0x79, 0x59, 0x68, 0x59, 0xd8, 0xdb, 0xcc, 0x64, 0xc2, 0x2f, 0x13, 0x28,
	0x7f, 0xad, 0xf1, 0xd4, 0x35, 0xdd, 0x1f, 0xd6, 0x64, 0xcd, 0x64, 0x64, 0x31, 0x27, 0xd4, 0x56,
	0x3f, 0x50, 0xbe, 0x05, 0xff, 0x81, 0x68, 0x35, 0x8e, 0x1e, 0xdd, 0x24, 0x2f, 0x41, 0x18, 0x52,
	0xc9, 0x43, 0xf2, 0x98, 0x6b, 0x61, 0x48, 0x5e, 0xc3, 0x39, 0xdf, 0x51, 0x82, 0xa3, 0x68, 0x64,
	0x09, 0x69, 0x8f, 0x3b, 0x95, 0x72, 0x16, 0x64, 0xe8, 0x6d, 0x9b, 0xb5, 0x47, 0x75, 0x16, 0x7b,
	0x6c, 0xaa, 0x15, 0x5c, 0x2d, 0x08, 0x8e, 0xcc, 0xe0, 0x70, 0xae, 0x06, 0x4a, 0x71, 0xa8, 0x32,
	0xb8, 0x67, 0x4a, 0xa6, 0x85, 0xe9, 0x03, 0x02, 0xad, 0x65, 0x44, 0xa6, 0x83, 0x94, 0xb7, 0x00,
	0x9b, 0xff, 0xc1, 0x4f, 0xf8, 0x3d, 0x92, 0x63, 0x4e, 0xa2, 0xf3, 0x98, 0x7c, 0x92, 0x7b, 0xfa,
	0x02, 0x60, 0xd6, 0x4b, 0x58, 0x27, 0x5f, 0x41, 0xbc, 0x93, 0xbc, 0xab, 0x97, 0x83, 0xeb, 0xe3,
	0xb5, 0x37, 0xf7, 0x27, 0xcf, 0xe3, 0x5b, 0xdb, 0x0b, 0xfe, 0xb7, 0xe7, 0x7d, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x74, 0xe1, 0xd3, 0x11, 0x4b, 0x01, 0x00, 0x00,
}
